### ISSUE TITLE
Automate release upload

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#1161]
We should make our lives easier and automatically upload the sdist to PyPI when a new release is tagged. Stealing from our MetPy Travis config:
```yml
deploy:
  - provider: pypi
    user: dopplershift
    password:
      secure: <ENCRYPTED_PW>
    distributions: sdist
    upload_docs: no
    on:
      repo: SciTools/cartopy
      python: 3.6
      condition: [MAKE SURE WE ONLY DO IT ONCE]
      tags: true
```

We might also want to automatically update the docs, but I’m not clear on what the current process for that is.
