### ISSUE TITLE
Unable to use SRTM source

### ISSUE THREAD

**Issue by flothesof** [SciTools/cartopy#789]
Hi,

I'm trying to grab elevation data from a SRTM source. 
I've modified the SRTM example to something a little more basic:

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from cartopy.io.srtm import SRTM3Source

plt.figure()
ax = plt.axes(projection=ccrs.PlateCarree())
# Define a raster source which uses the SRTM data and applies the
# shade function when the data is retrieved.
raster = SRTM3Source()
# Add the shaded SRTM source to our map with a grayscale colormap.
ax.add_raster(raster, cmap='Greys')
ax.set_extent([12, 13, 47, 48])
plt.show()
```

The problem is that I get an error ending like this:
`C:\Anaconda3\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    588 class HTTPDefaultErrorHandler(BaseHandler):
    589     def http_error_default(self, req, fp, code, msg, hdrs):
--> 590         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    591 
    592 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 401: Unauthorized`

I'm assuming this is the website where the tiles for the SRTM map are downloaded that doesn't respond in the way it should. I tried to replicate the call to urlopen with the following code:

`import urllib

url = 'http://e4ftl01.cr.usgs.gov/SRTM/SRTMGL1.003/2000.02.11/N47E012.SRTMGL1.hgt.zip'

urllib.request.urlopen(url)`

And get the same 401 error.

Any thoughts on how to solve this?

Thanks,
Florian

**Comment by QuLogic** [comment]
At what time did you try this? I think this is related to #769 where LPDAAC has an unseemly amount of probably unnecessary downtime.

**Comment by flothesof** [comment]
Hi Elliott,

Thanks for your reply.
I tried this at the time I filed the issue.
Is there any official page where I can check the downtime of the server?

Thanks,

Florian

**Comment by odermatt** [comment]
I get the same 401 error and I think it might be related to the new LP DAAC authorization requirement since July 20: https://lpdaac.usgs.gov/data_access/data_pool. I obtained the following urllib error:

```
try:
    urllib.request.urlopen('http://e4ftl01.cr.usgs.gov/SRTM/SRTMGL3.003/2000.02.11/N14W092.SRTMGL3.hgt.zip')
except urllib.error.HTTPError as e:
    print(e.headers)

    Server: nginx/1.4.7
    Date: Tue, 09 Aug 2016 11:10:21 GMT
    Content-Type: text/html; charset=utf-8
    Transfer-Encoding: chunked
    Connection: close
    Status: 401 Unauthorized
    X-Frame-Options: SAMEORIGIN
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    WWW-Authenticate: Basic realm="Please enter your Earthdata Login credentials. If you do not have a Earthdata Login, create one at https://urs.earthdata.nasa.gov//users/new"
    Cache-Control: no-cache
    X-Runtime: 0.042869
    X-Request-Id: ecb4f63b-157c-49dc-803e-73040edea6a0
```

Unfortunately the "Command Line Tips" document on the Earthdata site doesn't provide a Python example. I tried to create an authentification handler for cartopy's urllib.request, but didn't succeed. Other documents on the DAAC websites recommend using Pydap, but Pydap lacks a final Python 3 update and I'm not sure if there's already a recipe for 2.7 (https://github.com/pydap/pydap/issues/19).

Any help is appreciated!
